import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    onboard: true,
    name: '',
    resort: '',
    resortInfo: {},
    resortList: [
      {api: '', display: ''},
      {api: 'alpine', display: 'Alpine Meadows'},
      {api: "alta", display: "Alta"},
      {api: "alyeska", display: "Alyeska"},
      {api: "angel-fire", display: "Angel Fire"},
      {api: "abasin", display: "Arapaho Basin"},
      {api: "aspen-highlands", display: "Aspen Highlands"},
      {api: "aspen-mountain", display: "Aspen Mountain"},
      {api: "attitash", display: "Attitash"},
      {api: "beavercreek", display: "Beaver Creek"},
      {api: "big-sky", display: "Big Sky"},
      {api: "big-white", display: "Big White"},
      {api: "bluemountain", display: "Blue Mountain"},
      {api: "bolton-valley", display: "Bolton Valley"},
      {api: "boreal", display: "Boreal"},
      {api: "breck", display: "Breck"},
      {api: "brettonwoods", display: "Bretton Woods"},
      {api: "brianhead", display: "Brian Head"},
      {api: "bridger-bowl", display: "Bridger Bowl"},
      {api: "brighton", display: "Brighton"},
      {api: "bromley-mountian", display: "Brownley Mountain"},
      {api: "burke-mountain", display: "Burke Mountain"},
      {api: "buttermilk", display: "Buttermilk"},
      {api: "caberfae-peaks", display: "Caberfae Peaks"},
      {api: "camelback", display: "Camelback Mountain"},
      {api: "cannon", display: "Cannon"},
      {api: "cataloochee", display: "Cataloochee"},
      {api: "claviere", display: "Cesana Claviere"},
      {api: "sansicario", display: "Cesana San Sicario"},
      {api: "chinapeak", display: "China Peak"},
      {api: "copper", display: "Copper Mountain"},
      {api: "coronetpeak", display: "Coronet Peak"},
      {api: "courchevel", display: "Courchevel - 3 Vallees"},
      {api: "cranmore-mountain", display: "Cranmore"},
      {api: "cransmontana", display: "Crans-Montana"},
      {api: "crested-butte", display: "Crested Butte"},
      {api: "crystal-mountain", display: "Crystal Mountain"},
      {api: "deer-valley", display: "Deer Valley"},
      {api: "devils-head", display: "Devil's Head"},
      {api: "diamondpeak", display: "Diamond Peak"},
      {api: "falls-creek", display: "Falls Creek"},
      {api: "gore-mountain", display: "Gore Mountain"},
      {api: "grand-targhee", display: "Grand Targhee"},
      {api: "grouse", display: "Grouse Mountain"},
      {api: "gunstock", display: "Gunstock"},
      {api: "heavenly", display: "Heavenly"},
      {api: "hochfuegen", display: "Hochfugen"},
      {api: "homewood", display: "Homewood"},
      {api: "hoodoo", display: "Hoodoo"},
      {api: "hunter", display: "Hunter Mountain"},
      {api: "ischgl-silvretta-arena", display: "Ischgl - Silvretta"},
      {api: "jackson-hole", display: "Jackson Hole"},
      {api: "jay-peak", display: "Jay Peak"},
      {api: "jiminypeak", display: "Jiminy Peak"},
      {api: "june-mountain", display: "June Mountain"},
      {api: "keystone", display: "Keystone"},
      {api: "killington", display: "Killington"},
      {api: "king-pine", display: "King Pine"},
      {api: "kirkwood", display: "Kirkwood"},
      {api: "kitzbuehel", display: "Kitzbuehel"},
      {api: "laplangne", display: "La Plange"},
      {api: "larosiere", display: "La Rosiere"},
      {api: "lesarcs", display: "Les Arcs"},
      {api: "lesmenuires", display: "Les Menuieres"},
      {api: "loon", display: "Loon Mountain"},
      {api: "loveland", display: "Loveland"},
      {api: "mad-river-glen", display: "Mad River Glen"},
      {api: "mammoth-lakes", display: "Mammoth Mountain"},
      {api: "megeve", display: "Megeve"},
      {api: "meribel", display: "Meribel"},
      {api: "monarch", display: "Monarch Mountain"},
      {api: "montegenevre", display: "Montgenevre"},
      {api: "mount-sunapee", display: "Mount Sunapee"},
      {api: "mountsnow", display: "Mount Snow"},
      {api: "mt-buller", display: "Mount Buller"},
      {api: "mt-hotham", display: "Mount Hotham"},
      {api: "mt-spokane", display: "Mt Spokane"},
      {api: "mtbachelor", display: "Mount Bachelor"},
      {api: "mtbrighton", display: "Mt Brighton"},
      {api: "mthigh", display: "Mountain High"},
      {api: "mthood", display: "Mount Hood"},
      {api: "mtrose", display: "Mount Rose"},
      {api: "northstar", display: "Northstar"},
      {api: "okemo", display: "Okemo"},
      {api: "owlshead", display: "Owl's Head"},
      {api: "parkcity", display: "Park City"},
      {api: "pats-peak", display: "Pats Peak"},
      {api: "perisher", display: "Perisher"},
      {api: "pico", display: "Pico Mountain"},
      {api: "ragged-mountain", display: "Ragged Mountain"},
      {api: "red-lodge-mountain", display: "Red Lodge Mountain"},
      {api: "red-mountain", display: "Red Mountain"},
      {api: "sauze", display: "Sauze d'Oulx"},
      {api: "schweitzer", display: "Schweitzer"},
      {api: "sestriere", display: "Sestriere"},
      {api: "shawnee-mountain", display: "Shawnee Mountain"},
      {api: "shawnee-peak", display: "Shawnee Peak"},
      {api: "sierra", display: "Sierra at Tahoe"},
      {api: "silver-star", display: "Silver Star"},
      {api: "smuggs", display: "Smuggler's Notch"},
      {api: "snow-valley", display: "Snow Vallet"},
      {api: "snowbasin", display: "Snowbasin"},
      {api: "snowbird", display: "Snowbird"},
      {api: "snowmass", display: "Snowmass"},
      {api: "snowshoe", display: "Snowshoe Mountain"},
      {api: "solitude", display: "Solitude"},
      {api: "squaw", display: "Squaw Valley"},
      {api: "steamboat", display: "Steamboat"},
      {api: "stevens", display: "Stevens Pass"},
      {api: "stowe", display: "Stowe"},
      {api: "stratton", display: "Stratton"},
      {api: "sugarbowl", display: "Sugar Bowl"},
      {api: "sugarbush", display: "Sugarbush"},
      {api: "sugarloaf", display: "Sugarloaf"},
      {api: "sun-peaks", display: "Sun Peaks"},
      {api: "sunday-river", display: "Sunday River"},
      {api: "sunshine-village", display: "Sunshine Village"},
      {api: "sunvalley", display: "Sun Valley"},
      {api: "tahoe-donner", display: "Tahoe Donner"},
      {api: "taos", display: "Taos Ski Valley"},
      {api: "telluride", display: "Telluride"},
      {api: "vail", display: "Vail"},
      {api: "verbier", display: "Verbier"},
      {api: "waterville", display: "Waterville Valley"},
      {api: "whistler-blackcomb", display: "Whistler Blackcomb"},
      {api: "whiteface", display: "Whiteface"},
      {api: "wildcat", display: "Wildcat"},
      {api: "windham", display: "Windham Mountain"},
      {api: "winter-park", display: "Winter Park"},
      {api: "winterplace", display: "Winterplace"}
    ]
  },
  mutations: {
    submitOnboard (state, obj) {
      state.name = obj.name;
      state.resort = obj.resort;
      state.onboard = false
    },
    hasCookie (state) {
      state.onboard = false
    },
    changeResort (state, resort) {
      state.resort = resort;
    },
    changeName (state, name) {
      state.name = name;
    },
    resortInfo (state, info) {
      state.resortInfo = info;
    }
   }
})